name: flutter_messagerie_firebase
description: Un package de messagerie pour flutter et firebase
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.5.0
  flutter: ^3.24.0

dependencies:
  flutter:
    sdk: flutter
  fake_cloud_firestore: ^3.1.0
  cloud_firestore: ^5.6.1
  cloud_firestore_odm: ^1.0.0-dev.88
  equatable: ^2.0.7
  build_runner: ^2.4.14
  json_annotation: ^4.9.0
  date_repository:
    path: ../date_repository

dev_dependencies:
  cloud_firestore_odm_generator: ^1.0.0-dev.89
  flutter_test:
    sdk: flutter
  json_serializable: ^6.9.0
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0
